# Versão da especificação do Docker Compose
version: '3.8'

services:
  # Serviço: Webserver do Airflow (interface web)
  airflow-webserver:
    image: apache/airflow:2.10.4-python3.11  # Imagem oficial do Airflow com Python 3.11
    container_name: airflow_webserver        # Nome do contêiner
    restart: always                          # Reinicia automaticamente se o contêiner falhar
    depends_on:                              # Aguarda o scheduler e o banco estarem prontos
      - airflow-scheduler
      - airflow-db
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor         # Tipo de executor (usando sequencial para simplicidade)
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags       # Onde estão as DAGs dentro do contêiner
      - AIRFLOW__CORE__LOAD_EXAMPLES=False                 # Não carregar DAGs de exemplo
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080           # Porta onde a UI web vai rodar
    ports:
      - "8080:8080"                      # Mapeia a porta 8080 do contêiner para a porta 8080 do host
    volumes:
      - ../dags:/opt/airflow/dags        # Mapeia a pasta local de DAGs para o contêiner
      - ../output:/opt/airflow/output    # Mapeia a pasta local onde o CSV será salvo
    command: webserver                    # Comando que inicia o webserver do Airflow
    networks:
      - airflow_net                      # Rede para comunicação entre os contêineres

  # Serviço: Scheduler do Airflow (gerencia execução das DAGs)
  airflow-scheduler:
    image: apache/airflow:2.10.4-python3.11
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-db
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    volumes:
      - ../dags:/opt/airflow/dags
      - ../output:/opt/airflow/output
    command: scheduler                    # Comando que inicia o scheduler do Airflow
    networks:
      - airflow_net

  # Serviço: Banco de dados PostgreSQL usado pelo Airflow
  airflow-db:
    image: postgres:15                    # Imagem oficial do PostgreSQL
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow              # Usuário padrão do banco
      POSTGRES_PASSWORD: airflow          # Senha do usuário
      POSTGRES_DB: airflow                # Nome do banco usado pelo Airflow
    volumes:
      - pgdata:/var/lib/postgresql/data  # Volume para persistir os dados do banco
    networks:
      - airflow_net

# Volume nomeado para persistência dos dados do PostgreSQL
volumes:
  pgdata:

# Rede interna para que os contêineres consigam se comunicar entre si
networks:
  airflow_net:
