# Versão da especificação do Docker Compose (pode ser omitida nas versões modernas)
version: '3.8'

services:
  # Serviço responsável por inicializar o banco de dados do Airflow automaticamente
  airflow-init:
    image: apache/airflow:2.10.4-python3.11             # Usa a mesma imagem do Airflow
    container_name: airflow_init                        # Nome do contêiner de inicialização
    depends_on:
      - airflow-db                                      # Espera o banco estar pronto antes de executar
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor      # Mesmo executor das demais instâncias
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags    # Caminho das DAGs dentro do contêiner
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow  # Conexão com o PostgreSQL
      - AIRFLOW__LOGGING__REMOTE_LOGGING=False          # Desabilita o logging remoto
    volumes:
      - ../dags:/opt/airflow/dags                       # Mapeia as DAGs do host para o contêiner
      - ../output:/opt/airflow/output                   # Mapeia a pasta de saída (CSV) do host para o contêiner
    entrypoint: airflow db init                         # Comando que será executado ao rodar este serviço
    networks:
      - airflow_net

  # Serviço: Webserver do Airflow (interface web)
  airflow-webserver:
    image: apache/airflow:2.10.4-python3.11
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow-scheduler
      - airflow-db
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow  # Conexão com o PostgreSQL
      - AIRFLOW__LOGGING__REMOTE_LOGGING=False          # Desabilita o logging remoto
    ports:
      - "8080:8080"                                      # Porta mapeada para acesso à UI
    volumes:
      - ../dags:/opt/airflow/dags
      - ../output:/opt/airflow/output
    command: webserver
    networks:
      - airflow_net

  # Serviço: Scheduler do Airflow (responsável por agendar e iniciar tasks)
  airflow-scheduler:
    image: apache/airflow:2.10.4-python3.11
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-db
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow  # Conexão com o PostgreSQL
      - AIRFLOW__LOGGING__REMOTE_LOGGING=False          # Desabilita o logging remoto
    volumes:
      - ../dags:/opt/airflow/dags
      - ../output:/opt/airflow/output
    command: scheduler
    networks:
      - airflow_net

  # Serviço: Banco de dados PostgreSQL usado pelo Airflow
  airflow-db:
    image: postgres:15
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow                           # Nome do usuário do banco
      POSTGRES_PASSWORD: airflow                       # Senha do banco
      POSTGRES_DB: airflow                             # Nome do banco
    volumes:
      - pgdata:/var/lib/postgresql/data                # Volume para persistência dos dados
    networks:
      - airflow_net

# Volume nomeado para persistência dos dados do PostgreSQL
volumes:
  pgdata:

# Rede interna para comunicação entre os contêineres
networks:
  airflow_net:
